spring:
  application:
    name: employee-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
