server:
  port: 8081

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
